training:
  epochs: 30
  learning_rate: 0.0004
  batch_size: 32
  image_size: 128
  in_channels: 3
  out_channels: 3
  timesteps: 1000
  beta_schedule: "squaredcos_cap_v2"
  num_inference_steps: 100

model:
  block_out_channels: [64, 128, 128, 256]
  layers_per_block: 2
  down_block_types:
    - "DownBlock2D"
    - "DownBlock2D"
    - "AttnDownBlock2D"
    - "AttnDownBlock2D"
  up_block_types:
    - "AttnUpBlock2D"
    - "AttnUpBlock2D"
    - "UpBlock2D"
    - "UpBlock2D"

wandb:
  project: "diffusion-arcade"
  entity: "adriana-orellana-torrico"
  run_name: "diffusion-model"