default_config: &default_config
  epochs: 20
  learning_rate: 0.0002
  batch_size: 64
  image_size: 64
  timesteps: 1000
  beta_schedule: "squaredcos_cap_v2"
  scheduler: "DDPM"
  num_inference_steps: 100
  output_dir: "models"
  hf_org: "DiffusionArcade"
  action_embedding_size: 256
  num_actions: 3
  context_length: 8

game:
  <<: *default_config
  model_path: "/home/smyth/DiffusionArcade/notebooks/models/final/model_20250531_165053_epochs_69.pt"
  in_channels: 8
  out_channels: 1
